[PNPG-250] feat: DELETE_OLD_PG_MANAGERS activity implementation
pagopa/selfcare-onboarding pull request #544
Opened 2024-10-13 11:12 UTC by empassaro

#### List of Changes

DELETE_OLD_PG_MANAGERS activity implementation

#### Motivation and Context

This activity is responsible of finding all the managers of an institution and check on related registry (ADE or INFOCAMERE) if they are still managers. In case they are not managers anymore will be deleted from institution.

#### How Has This Been Tested?

local env

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-10-13 12:18 UTC, andrea-putzu commented on apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctions.java
> +    public void deleteOldPgManagers(@DurableActivityTrigger(name = "onboardingString") String onboardingString, final ExecutionContext context) {
why do we need a dedicated function for manager pnpg?

2024-10-13 12:18 UTC, andrea-putzu commented on apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionService.java
> +    void deleteOldPgManagers(Onboarding onboarding);
Ditto

2024-10-16 10:27 UTC, manuraf requested changes

2024-10-16 10:27 UTC, manuraf commented on apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefault.java
> +                throw new GenericOnboardingException("Impossible to delete user: " + uid);
you could providing more context can aid in debugging and maintenance....for ex: String.format("Failed to delete user '%s' from product '%s' in institution '%s'", uid, productId, institutionId));

2024-10-16 11:00 UTC, manuraf approved these changes

2024-10-17 15:33 UTC, merged