[SELC-2864] Feat: added API for get Onboarding with optional filters
pagopa/selfcare-onboarding pull request #70
Opened 2023-12-14 17:27 UTC by flaminiaScarciofolo

#### List of Changes

Added API for get Onboarding with optional filters and pagination

#### Motivation and Context

An API is needed to retrieve onboardings

#### How Has This Been Tested?
tested in dev mode.
Called new API with single, multiple or none filters, and with different pageNumber and pageSize.

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-12-15 08:02 UTC, manuraf requested changes

2023-12-15 08:15 UTC, flaminiaScarciofolo commented on apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
> +                .onItem().transformToUni(ignore -> onboardingService.onboardingGet(productId, taxCode, status, from, to, page, size));
You are right. At first I thought I had to use logged user to filter onboarding, then this filter was eliminated but method was not.

2023-12-15 12:18 UTC, manuraf commented on apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
> +    @Disabled
why is it disabled?

2023-12-18 13:22 UTC, manuraf approved these changes

2023-12-18 13:23 UTC, merged